arch:
- amd64
codenotary: agonist02_stiel@icloud.com
description: Code Server experience integrated in the Home Assistant frontend.
devices:
- /dev/net/tun
docker_api: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
image: ghcr.io/elcajon/code-server/{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
- config:rw
- ssl:rw
- addons:rw
- media:rw
- share:rw
- backup:rw
name: Code Server
panel_icon: mdi:code-json
privileged:
- NET_ADMIN
schema:
  init_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
services:
- mysql:want
- mqtt:want
slug: code-server
startup: services
url: https://github.com/elcajon/addon-code-server
version: 27eaf8f
