arch:
- amd64
description: Simplelogin self-hosted Server
image: ghcr.io/elcajon/simplelogin/{arch}
init: false
map:
- ssl:rw
- share:rw
name: Simplelogin
ports:
  25/tcp: 25
  443/tcp: 443
  80/tcp: 80
ports_description:
  25/tcp: SMTP
  443/tcp: Web interface https
  80/tcp: Web interface http
slug: simplelogin
url: https://github.com/elcajon/addon-simplelogin
version: a05156c
