---
name: Lint

# yamllint disable-line rule:truthy
permissions:
  contents: read

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/repository-lint.yaml@main
