---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

jobs:
  publish:
    name: Publish add-on update
    runs-on: ubuntu-latest
    steps:
      - name: 🔣 Generate App Token
        uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
      - name: 🔂 Wait for other runs to complete
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 1200
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1.2.2
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ steps.token.outputs.token }}
