---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["update"]

concurrency:
  group: queue

jobs:
  publish:
    name: Publish add-on update
    runs-on: ubuntu-latest
    steps:
      - name: 🔐 Load 1Password Github App secret
        uses: 1password/load-secrets-action@v1.2.0
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          APP_ID: "op://CI/Github App/Benutzername"
          APP_SECRET: "op://CI/Github App/elcajon-token-app.2022-08-31.private-key.pem"
      - name: 🔣 Generate App Token
        uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ env.APP_SECRET }}
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1.2.5
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ steps.token.outputs.token }}
