---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

jobs:
  workflows:
    steps:
      - name: 🔣 Generate App Token
        uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
      - uses: hassio-addons/workflows/.github/workflows/repository-updater.yaml@main
        secrets:
          UPDATER_TOKEN: ${{ steps.token.outputs.token }}
