---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["update"]

jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://CI/github-token/Anmeldedaten
  workflows:
    needs: credentials
    uses: hassio-addons/workflows/.github/workflows/repository-updater.yaml@main
    secrets:
      UPDATER_TOKEN: ${{ needs.credentials.steps.op-load-secret.outputs.GITHUB_TOKEN }}
